[theme]
primaryColor = "#1E3D59"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#E6EEF8"
textColor = "#1E3D59"

[server]
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
