# Secrets configuration
[postgres]
host = "${PGHOST}"
port = "${PGPORT}"
dbname = "${PGDATABASE}"
user = "${PGUSER}"
password = "${PGPASSWORD}"

[tab]
bearer_token = "${TAB_BEARER_TOKEN}"

[punting_form]
api_key = "${PUNTING_FORM_API_KEY}"

[openai]
api_key = "${OPENAI_API_KEY}"

[database]
url = "${DATABASE_URL}"
